var_docker_image: &var_docker_image popcornpool/chrome-node-yarn
var_dependency_cache_key: &var_dependency_cache_key dependency-cache-{{ checksum "yarn.lock" }}-1.0
var_dependency_cache_path: &var_dependency_cache_path ~/.cache/yarn

# After checkout, rebase on top of master.
# Similar to travis behavior, but not quite the same.
# See https://discuss.circleci.com/t/1662
anchor_post_checkout: &anchor_post_checkout
  post: git pull --ff-only origin "refs/pull/${CIRCLE_PULL_REQUEST//*pull\//}/merge"

anchor_job_common: &anchor_job_common
  docker:
    - image: *var_docker_image

anchor_print_versions: &anchor_print_versions
  name: Print versions
  command: |
    node --version
    npm --version
    yarn --version

anchor_install_deps: &anchor_install_deps
  name: Install Dependencies
  command: yarn --pure-lockfile --non-interactive

version: 2
jobs:
  lint:
    <<: *anchor_job_common
    steps:
      - checkout:
          <<: *anchor_post_checkout
      - run: *anchor_print_versions
      - restore_cache:
          key: *var_dependency_cache_key
      - run: *anchor_install_deps
      - save_cache:
          key: *var_dependency_cache_key
          paths:
            - *var_dependency_cache_path
      - run:
          name: Format check
          command: npm run format:check
      - run:
          name: Lint
          command: npm run lint
  build:
    <<: *anchor_job_common
    steps:
      - checkout:
          <<: *anchor_post_checkout
      - run: *anchor_print_versions
      - restore_cache:
          key: *var_dependency_cache_key
      - run: *anchor_install_deps
      - save_cache:
          key: *var_dependency_cache_key
          paths:
            - *var_dependency_cache_path
      - run:
          name: Build (prod)
          command: npm run build
  test:
    <<: *anchor_job_common
    steps:
      - checkout:
          <<: *anchor_post_checkout
      - run: *anchor_print_versions
      - restore_cache:
          key: *var_dependency_cache_key
      - run: *anchor_install_deps
      - save_cache:
          key: *var_dependency_cache_key
          paths:
            - *var_dependency_cache_path
      - run:
          name: Test
          command:  npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - lint
